const localisation: Record<string, string> = {
  about: 'Jakékoliv připomínky či nápady neváhejte sdělit na:',
  affirmative: 'Afirmace',
  cancel: 'Zrušit',
  close: 'Zavřít',
  ok: 'Ano',
  mode: 'Režim zobrazení',
  modeClassic: 'Klasický',
  modeLinear: 'Jednoduchý',
  negative: 'Negace',
  pause: 'Pozastavit',
  preptime: 'Přípravný čas',
  pwaPromptIOSAddToHomescreen: 'Vyberte možnost Přidat na plochu',
  pwaPromptIOSDone: 'Potvrďte instalaci a je hotovo!',
  pwaPromptIOSOpenMenu: 'Otevřete menu prohlížeče',
  pwaPromptIOSParagraph: 'Abyste měli stopky uložené mezi aplikacemi a mohli je používat offline, je potřeba je nainstalovat:',
  pwaPromptIOSTitle: 'Nainstalujte si Debatní stopky',
  reset: 'Resetovat',
  resetConfirm: 'Opravdu si přejete stopky resetovat?',
  settings: 'Nastavení',
  start: 'Spustit',
  themeColour: 'Barevný režim',
  themeColourAuto: 'Auto',
  themeColourDark: 'Tmavý',
  themeColourLight: 'Světlý',
  title: 'Debatní stopky',
};

export default localisation;
